# Copyright 2016 Cisco Systems, Inc_
#
# Licensed under the Apache License, Version 2_0 (the "License"); you may
# not use this file except in compliance with the License_ You may obtain
# a copy of the License at
#
#      http://www_apache_org/licenses/LICENSE-2_0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied_ See the
# License for the specific language governing permissions and limitations
# under the License_

- name: Creating the directory structure to store topologies jars
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ topologies_folder }}"
    - "{{ topologies_folder }}/jars"
    - "{{ topologies_folder }}/confs"
  tags:
    - onprem-installation

- name: Install jq
  apt: pkg=jq update_cache=yes
  tags:
    - onprem-installation

- name: copy jar
  shell: cp {{ role_path }}/files/storm-topologies-0.9.6.jar {{ topologies_folder }}/jars/storm_topologies.jar

- name: Add Deploying script
  template:
    src: deploy-topologies.py.j2
    dest: "{{ topologies_folder }}/deploy-topologies.py"
    mode: 0755
  tags:
    - onprem-installation
    - onprem-configuration

- name: Copy Logs deploying conf
  copy:
    src: templates/logs-topology.yml.j2
    dest: "{{ topologies_folder }}/confs/logs-topology.yml.j2"
  tags:
    - onprem-installation
    - onprem-configuration

- name: Make sure pip is installed
  apt:
    name: python3-pip
    update_cache: yes
  tags:
    - onprem-installation

- name: Install jinja
  pip:
    name: jinja2
    executable: pip3
  tags:
    - onprem-installation

- name: Deploying Logs Topology
  shell: "{{ topologies_folder }}/deploy-topologies.py"
  environment:
    TOPOLOGY_NAME: 'Logs'
    ZOOKEEPER_HOSTS: "{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_ssh_host'] }}{% if not loop.last %}/{% endif %}{% endfor %}"
    KAFKA_HOSTS: "{% for host in groups['kafka'] %}{{ hostvars[host]['ansible_ssh_host'] }}{% if not loop.last %}/{% endif %}{% endfor %}"
    ELASTICSEARCH_HOST: "{{hostvars[groups['elasticsearch_data'][0]]['ansible_ssh_host']}}"
  when: groups['elasticsearch_data'] is defined and sre_influxdb_addr is not defined
  ignore_errors: yes
  tags:
    - onprem-configuration
