- stat: path=/dev/xvdb
  register: device_exists

- name: Unmounting Volume
  mount: name="{{ volume_mount_point }}" src=/dev/xvdb fstype=ext4 state=absent
  when: device_exists.stat.exists == True
  tags:
    - onprem-configuration
  
- name: Formatting Volume
  filesystem: fstype=ext4 dev=/dev/xvdb force=yes
  when: device_exists.stat.exists == True
  tags:
    - onprem-configuration

- name: Mounting the volume
  mount: name="{{ volume_mount_point }}" src=/dev/xvdb fstype=ext4 state=mounted
  when: device_exists.stat.exists == True
  tags:
    - onprem-configuration

- name: Adding the volume to fstab
  mount: name="{{ volume_mount_point }}" src=/dev/xvdb fstype=ext4 state=present
  when: device_exists.stat.exists == True
  tags:
    - onprem-configuration
