---
- name: plugins | Removing Old Plugins
  shell: bin/elasticsearch-plugin remove {{ item.name }}
    chdir={{ elasticsearch_home_dir }}
  when: item.name is defined and item.reinstall is defined and item.reinstall == True
  with_items: "{{elasticsearch_plugins}}"
  ignore_errors: yes
  tags:
    - onprem-installation

- name: plugins | Installing Plugins
  shell: bin/elasticsearch-plugin install {{ item.name }} {{ '-url ' + item.url if item.url is defined else '' }}
    chdir={{ elasticsearch_home_dir }}
  when: item.download_only is not defined
  with_items: "{{elasticsearch_plugins}}"
  register: plugins_installed
  changed_when: "'Installed' in plugins_installed.stdout"
  failed_when: "plugins_installed.rc != 0 and plugins_installed.stdout.find('already exists. To update the plugin') == -1"
  tags:
    - onprem-installation

- name: plugins | Ensure Paths for Download only Plugins
  file:
    path="{{ elasticsearch_plugin_dir }}/{{ item.name }}"
    state=directory
  when: item.download_only is defined and item.name is defined
  with_items: elasticsearch_plugins
  tags:
    - onprem-installation

- name: plugins | Download only Plugins
  get_url:
    url={{ item.url }}
    dest={{ elasticsearch_plugin_dir }}/{{ item.name }}
  when: item.download_only is defined and item.name is defined
  with_items: elasticsearch_plugins
  ignore_errors: yes
  tags:
    - onprem-installation
