---

- name: post-run | Ensure plugins directory permission are correct
  file:
    path="{{ elasticsearch_plugin_dir }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes
  tags:
    - onprem-configuration

- name: post-run | Ensure Elasticsearch is running and started on boot
  service:
    name=elasticsearch
    enabled={{ elasticsearch_service_startonboot }}
    state={{ elasticsearch_service_state }}
  when: installed_version.stat.exists
  tags:
    - onprem-configuration

# Flush handlers to restart elastic if needed
- meta: flush_handlers
  tags:
    - onprem-configuration

- name: post-run | Check http port is open and running version. timeout 160s
  wait_for:
    host={{ ansible_ssh_host if elasticsearch_network_bind_host is not defined or elasticsearch_network_bind_host == '0.0.0.0' else elasticsearch_network_bind_host }}
    port={{ elasticsearch_network_http_port | default('9200') }}
    timeout=160
  when: elasticsearch_service_state == "started"
  tags:
    - onprem-configuration

- name: post-run | Adding geo-ip template sh file.
  template:
    src=geo_ip_template.sh.j2
    dest={{ elasticsearch_conf_dir }}/geo_ip_template.sh
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  when: elasticsearch_conf_dir is defined
  tags:
    - onprem-configuration

- name: post-run | Adding template for geoip field
  shell: bash {{ elasticsearch_conf_dir }}/geo_ip_template.sh
  when: elasticsearch_conf_dir is defined
  tags:
    - onprem-configuration
